package com.example.visitsacompose.common.model

import com.example.visitsacompose.R
import com.example.visitsacompose.common.model.enum.SectionEnum
import com.example.visitsacompose.common.model.enum.TourType

data class HomeItemModel(
    val id: Int,
    val title: String,
    val type: SectionEnum,
    val address: String,
    val rating: Double,
    val price: Int,
    val image: Int,
    val city: String,
    val cost: String,
    val isRecommended: Boolean = false,
    val details: String? = null,
    val url: String? = null,
    val isTour: Boolean = false,
    val tourType: TourType? = null
)

fun displayHomeItems(): List<HomeItemModel> {
    return listOf(
        HomeItemModel(
            id = 1,
            title = "Hotel Central",
            type = SectionEnum.HOTEL,
            address = "Ćumurija 8",
            rating = 4.3,
            price = 3,
            image = R.drawable.ic_hotel_central,
            city = "Sarajevo",
            cost = "60$",
            isRecommended = true,
            details = "Hotel Central is a charming and centrally located hotel in the heart of Sarajevo. With its warm and welcoming atmosphere, it offers comfortable rooms, equipped with modern amenities, ensuring a pleasant stay for guests. The hotel features a restaurant serving delicious local and international cuisine, a cozy bar, and a 24-hour front desk. Its convenient location allows easy access to major attractions, shopping areas, and cultural sites in the city.",
            url = "https://www.hotelcentral.ba/"
        ),
        HomeItemModel(
            id = 2,
            title = "Hotel Holiday",
            type = SectionEnum.HOTEL,
            address = "Zmaja od Bosne 4",
            rating = 4.5,
            price = 3,
            image = R.drawable.ic_hotel_holiday,
            city = "Sarajevo",
            cost = "45$",
            isRecommended = true,
            details = "Hotel Holiday is a well-established hotel situated in a tranquil area of Sarajevo, offering a serene and relaxing atmosphere for guests. The hotel boasts spacious and elegantly furnished rooms, providing a comfortable retreat after a day of exploring the city. Guests can enjoy a range of amenities, including a fitness center, a sauna, and an on-site restaurant serving delectable dishes. The hotel's attentive staff and scenic surroundings make it an ideal choice for a peaceful stay.",
            url = "https://www.hoteleuropegroup.ba/ba/holiday"
        ),
        HomeItemModel(
            id = 3,
            title = "Hotel Europe",
            type = SectionEnum.HOTEL,
            address = "Vladislava Skarića 5",
            rating = 4.8,
            price = 4,
            image = R.drawable.ic_hotel_europe,
            city = "Sarajevo",
            cost = "34$",
            isRecommended = true,
            details = "Hotel Europa is a modern and stylish hotel located in the city center of Sarajevo. With its sleek design and contemporary decor, it offers a sophisticated and comfortable experience for guests. The hotel provides well-appointed rooms with modern amenities, a fitness center, and a restaurant serving a fusion of international and Bosnian cuisine. Its central location allows for easy access to attractions, shopping districts, and vibrant nightlife, making it a convenient choice for travelers.",
            url = "https://www.hoteleuropegroup.ba/ba/europe"
        ),
        HomeItemModel(
            id = 4,
            title = "Swissôtel",
            type = SectionEnum.HOTEL,
            address = "Vrbanja 1",
            rating = 4.9,
            price = 5,
            image = R.drawable.ic_hotel_swiss,
            city = "Sarajevo",
            cost = "94$",
            isRecommended = false,
            details = "Located in the city center, where hospitality is part of the nature of Bosnia and Herzegovina. Swissotel Sarajevo offers contemporary and modern designed rooms with stunning views, free Wi-Fi, state of the art Wellness and Spa facilities, as well as two restaurants. All of the 218 comfortable rooms and suites of the Swissotel Sarajevo feature a flat-screen TV, coffee and tea making facilities, large windows with accompanying seating duvets, walk in shower and an electronic safe.",
            url = "https://www.swissotel.com/hotels/sarajevo/?cmpid=google_ssj_search-branded-ww_branded-e-revsh&gclid=CjwKCAjwyeujBhA5EiwA5WD7_Y-ZFWtFMAV66O4rFtnBEM6OvAAmoEbW2oKyYsGogP-kykzsLGGxrhoCdwIQAvD_BwE"
        ),
        HomeItemModel(
            id = 5,
            title = "Radon Plaza",
            type = SectionEnum.HOTEL,
            address = "Dzemala Bijedica 185",
            rating = 4.6,
            price = 4,
            image = R.drawable.ic_hotel_radon,
            city = "Sarajevo",
            cost = "60$",
            isRecommended = false,
            details = "Hotel Radon Plaza is a luxurious and upscale hotel situated in Sarajevo's business district. With its elegant interiors and top-notch facilities, it caters to discerning travelers seeking comfort and convenience. The hotel offers spacious and tastefully decorated rooms, a fitness center, a spa, and multiple dining options, including a fine dining restaurant and a stylish lounge bar. Its proximity to the airport and excellent business amenities make it a popular choice for both business and leisure travelers.",
            url = "https://radonplaza.ba/"
        ),
        HomeItemModel(
            id = 6,
            title = "Malak Regency",
            type = SectionEnum.HOTEL,
            address = "Hrasnička cesta bb",
            rating = 4.4,
            price = 4,
            image = R.drawable.ic_hotel_malak,
            city = "Ilidža",
            cost = "38$",
            isRecommended = false,
            details = "Hotel Malak is a cozy boutique hotel located in the heart of Sarajevo's old town. With its charming and traditional Bosnian architecture, it provides a unique and authentic experience for guests. The hotel offers well-appointed rooms with rustic decor, reflecting the city's cultural heritage. Guests can enjoy a hearty Bosnian breakfast, relax in the hotel's courtyard, and explore the nearby historic attractions and bustling markets. Hotel Malak offers a warm and personalized stay for those seeking a taste of Sarajevo's traditional hospitality.",
            url = "https://www.guestreservations.com/hotel-malak-regency/booking?gclid=CjwKCAjwyeujBhA5EiwA5WD7_WWw5dRIlxs0Ekb_RZInf1bk4ZfnRVoGRzUVIgfTRcw5i01mX0SavBoCrh0QAvD_BwE"
        ),
        HomeItemModel(
            id = 7,
            title = "Avlija",
            type = SectionEnum.RESTAURANT,
            address = "Avde Sumbula 2",
            rating = 4.7,
            price = 3,
            image = R.drawable.ic_restaurant_avlija,
            city = "Sarajevo",
            cost = "34$",
            isRecommended = true,
            url = "https://www.avlija.ba/",
            details = "Avlija is a charming and atmospheric restaurant tucked away in Sarajevo's old town. It offers a traditional Bosnian dining experience in a picturesque courtyard setting. Guests can savor a variety of authentic Bosnian dishes prepared with local ingredients, including cevapi (grilled meat), burek (savory pastry), and dolma (stuffed vegetables). The restaurant's warm and rustic ambiance, combined with its delicious cuisine, creates a memorable dining experience that captures the essence of Bosnian hospitality."
        ),
        HomeItemModel(
            id = 8,
            title = "BarSa",
            type = SectionEnum.RESTAURANT,
            address = "Despićeva 7",
            rating = 4.8,
            price = 4,
            image = R.drawable.ic_restaurant_barsa,
            city = "Sarajevo",
            cost = "34$",
            isRecommended = true,
            url = "https://www.mein-mittagsmenue.at/en/restaurants/barsa/overview",
            details = "Barsa is a trendy and modern restaurant located in the heart of Sarajevo. It specializes in contemporary Mediterranean cuisine with a creative twist. The restaurant's sleek interior, stylish decor, and vibrant atmosphere create an inviting space for diners. Guests can enjoy a diverse menu featuring fresh seafood, grilled meats, flavorful salads, and imaginative vegetarian options. Barsa also boasts an extensive selection of wines and cocktails, making it an ideal spot for a sophisticated and enjoyable dining experience."
        ),
        HomeItemModel(
            id = 9,
            title = "Petica",
            type = SectionEnum.RESTAURANT,
            address = "Bravadžiluk 21",
            rating = 4.6,
            price = 2,
            image = R.drawable.ic_restaurant_petica,
            city = "Sarajevo",
            cost = "34$",
            isRecommended = true,
            url = "https://ferhatovic.ba/",
            details = "Petica is a popular restaurant in Sarajevo known for its delicious Balkan cuisine and relaxed atmosphere. The restaurant offers a cozy setting with a mix of rustic and contemporary decor. Diners can indulge in a range of traditional Bosnian dishes, such as pita (savory pie), Bosnian kebabs, and hearty stews. Petica takes pride in using locally sourced ingredients and preparing dishes with traditional recipes, providing guests with an authentic taste of Bosnian gastronomy."
        ),
        HomeItemModel(
            id = 10,
            title = "Blind Tiger",
            type = SectionEnum.RESTAURANT,
            address = "Dalmatinska 2",
            rating = 4.6,
            price = 2,
            image = R.drawable.ic_restaurant_tiger,
            city = "Sarajevo",
            cost = "34$",
            url = "https://blind-tiger-sarajevo.business.site/",
            details = "Blind Tiger is a trendy and eclectic restaurant and bar in Sarajevo, inspired by the Prohibition era. The establishment features a speakeasy-style ambiance with dim lighting, vintage decor, and live music performances. The menu offers a fusion of international flavors and innovative cocktails, showcasing the creativity of the talented chefs and mixologists. Blind Tiger's unique atmosphere, combined with its delicious food and inventive drinks, creates an unforgettable and immersive dining experience."
        ),
        HomeItemModel(
            id = 11,
            title = "Cakum Pakum",
            type = SectionEnum.RESTAURANT,
            address = "Kaptol 10",
            rating = 4.7,
            price = 3,
            image = R.drawable.ic_restaurant_cakum,
            city = "Sarajevo",
            cost = "34$",
            url = "https://foursquare.com/v/cakum-pakum/52409169498e0b3de6fdcfc4",
            details = "Cakum Pakum is a lively and vibrant restaurant located in the heart of Sarajevo's bustling market district. Known for its street food-inspired menu, it offers a variety of quick bites and local specialties. Guests can enjoy mouthwatering grilled meats, savory pastries, and flavorful sandwiches, all prepared with fresh ingredients and traditional techniques. The restaurant's casual and energetic atmosphere, coupled with its affordable prices, makes it a popular choice for a quick and tasty meal in Sarajevo."
        ),
        HomeItemModel(
            id = 12,
            title = "Klopa",
            type = SectionEnum.RESTAURANT,
            address = "Trg Fra Grge Martića 4",
            rating = 4.6,
            price = 2,
            image = R.drawable.ic_restaurant_klopa,
            city = "Sarajevo",
            cost = "20$",
            url = "https://www.mein-mittagsmenue.at/bs/user/8",
            details = "Klopa is a cozy and family-friendly restaurant that celebrates the rich culinary heritage of Bosnia and Herzegovina. Located in a traditional house, it offers a warm and inviting atmosphere with rustic decor and friendly service. The menu features a range of traditional Bosnian dishes, including hearty soups, comforting stews, and savory pies. Klopa takes pride in using locally sourced ingredients, ensuring the freshness and authenticity of its dishes. The restaurant's warm ambiance and delicious food make it a favorite among locals and visitors alike."
        ),
        HomeItemModel(
            id = 13,
            title = "Silver & Smoke Club",
            type = SectionEnum.CLUB,
            address = "Zelenih beretki 12",
            rating = 4.5,
            price = 2,
            image = R.drawable.ic_club_silver,
            city = "Sarajevo",
            cost = "30$",
            isRecommended = true,
            url = "https://www.nightflow.com/silver-smoke-sarajevo/",
            details = "Located in the heart of Sarajevo, Silver & Smoke Club is a popular nightlife destination known for its energetic atmosphere and diverse music selection. With a spacious dance floor, impressive light displays, and a lineup of talented DJs, this club caters to various music tastes, including electronic, house, and commercial hits. The club also features occasional live performances and themed parties, ensuring a memorable night out for partygoers."
        ),
        HomeItemModel(
            id = 14,
            title = "Aquarius Club",
            type = SectionEnum.CLUB,
            address = "Zmaja od Bosne 13",
            rating = 4.6,
            price = 2,
            image = R.drawable.ic_club_aquarius,
            city = "Sarajevo",
            cost = "30$",
            url = "https://www.aquariusvils.com/",
            details = "Situated along the banks of the Miljacka River, Aquarius Club offers a unique nightlife experience with its picturesque location and vibrant ambiance. This open-air club boasts a large outdoor terrace overlooking the river, creating a perfect setting for warm summer nights. The club features a mix of live bands, DJs, and themed events, playing a wide range of music genres, from pop and rock to electronic and R&B. Aquarius Club is a go-to spot for both locals and tourists looking to enjoy Sarajevo's nightlife in a scenic setting.",
            isRecommended = true
        ),
        HomeItemModel(
            id = 15,
            title = "Dom Mladih",
            type = SectionEnum.CLUB,
            address = "Terezija bb",
            rating = 4.7,
            price = 2,
            image = R.drawable.ic_club_mladih,
            city = "Sarajevo",
            cost = "30$",
            url = "https://www.skenderija.ba/index.php/dommladih",
            details = "Dom Mladih, meaning \"Youth Center\" in English, is a renowned cultural hub in Sarajevo that also houses a popular nightclub. With a long-standing history, this venue hosts various music events, concerts, and DJ performances catering to different tastes and genres. The club's spacious dance floor, impressive sound system, and lively atmosphere make it a favorite among Sarajevo's youth. Dom Mladih regularly organizes themed parties, showcasing a mix of local and international talent."
        ),
        HomeItemModel(
            id = 16,
            title = "Mr & Mrs Cue",
            type = SectionEnum.CLUB,
            address = "Vilsonovo šetalište 13",
            rating = 4.6,
            price = 2,
            image = R.drawable.ic_club_mrque,
            city = "Sarajevo",
            cost = "30$",
            url = "https://www.spottedbylocals.com/sarajevo/mr-mrs-cue/",
            details = "Mr & Mrs Cue is a trendy and vibrant billiards and entertainment venue located in Sarajevo. This stylish establishment offers a unique blend of billiards, socializing, and nightlife. With its sleek and modern interior, Mr & Mrs Cue provides a comfortable and inviting space for both casual players and enthusiasts alike. The venue features a range of well-maintained billiard tables where guests can showcase their skills and enjoy friendly competitions. Additionally, Mr & Mrs Cue offers a variety of delicious food and refreshing drinks, making it the perfect spot to unwind and socialize with friends. Whether you're a billiards enthusiast or simply looking for a fun and relaxed atmosphere, Mr & Mrs Cue provides an enjoyable and entertaining experience in Sarajevo."
        ),
        HomeItemModel(
            id = 17,
            title = "Underground Club",
            type = SectionEnum.CLUB,
            address = "Maršala Tita 56",
            rating = 4.6,
            price = 2,
            isRecommended = true,
            image = R.drawable.ic_club_underground,
            city = "Sarajevo",
            cost = "30$",
            url = "https://www.nightflow.com/underground-club-sarajevo/",
            details = "As its name suggests, Underground Club is a popular venue for lovers of underground electronic music in Sarajevo. Nestled in the basement of an old building, this intimate club creates an authentic underground atmosphere. With its focus on techno, house, and experimental beats, it draws a dedicated community of music enthusiasts and hosts regular DJ performances and themed events. The dimly lit space and pulsating rhythms make Underground Club a must-visit destination for those seeking a unique and edgy nightlife experience."
        ),
        HomeItemModel(
            id = 18,
            title = "Jazzbina",
            type = SectionEnum.CLUB,
            address = "Maršala Tita 38",
            rating = 4.7,
            price = 2,
            image = R.drawable.ic_club_jazbina,
            city = "Sarajevo",
            cost = "30$",
            url = "https://sarajevo.travel/ba/sta-raditi/jazzbina-sarajevo/991",
            details = "Jazzbina is a legendary jazz club that has been a staple of Sarajevo's music scene for decades. Known for its cozy and intimate setting, the club offers live jazz performances by talented local musicians, as well as occasional international guest artists. Jazzbina's laid-back ambiance, candlelit tables, and extensive selection of drinks make it a haven for jazz lovers and those seeking a relaxed and sophisticated evening of live music."
        ),
        HomeItemModel(
            id = 19,
            title = "Historical Heritage Walk",
            type = SectionEnum.TOUR,
            tourType = TourType.POPULAR,
            rating = 4.6,
            address = "Sarajevo",
            price = 1,
            image = R.drawable.ic_tour1,
            city = "Sarajevo",
            cost = "9$",
            isTour = true,
            isRecommended = true,
            details = "Immerse yourself in the rich history of Sarajevo as you explore its iconic landmarks and historical sites. This guided walking tour takes you through the enchanting old town, where you'll discover the ancient Bascarsija Square, visit the grand Gazi Husrev-beg Mosque, explore the intriguing Sarajevo City Hall, and learn about the city's fascinating past at the Sarajevo Museum. Experience the blend of Ottoman, Austro-Hungarian, and modern influences that have shaped this captivating city."
        ),
        HomeItemModel(
            id = 20,
            title = "Tastes of Sarajevo",
            type = SectionEnum.TOUR,
            tourType = TourType.RECOMMENDED,
            rating = 4.8,
            address = "Sarajevo",
            isTour = true,
            price = 3,
            image = R.drawable.ic_tour2,
            city = "Sarajevo",
            cost = "30$",
            isRecommended = true,
            details = "Embark on a culinary adventure through Sarajevo's vibrant food scene. This gastronomic tour introduces you to the city's diverse flavors and traditionaldishes. Indulge in delicious cevapi, a local specialty of grilled meat served with warm flatbread, or savor the hearty flavors of Sarajevski Stew. Explore the bustling markets and try authentic Bosnian sweets like baklava. Along the way, your knowledgeable guide will share insights into the cultural significance of the food and its connection to Sarajevo's history."
        ),
        HomeItemModel(
            id = 21,
            title = "Sarajevo Panorama",
            type = SectionEnum.TOUR,
            tourType = TourType.POPULAR,
            rating = 4.9,
            address = "Sarajevo",
            price = 3,
            image = R.drawable.ic_tour3,
            city = "Sarajevo",
            cost = "20$",
            isTour = true,
            isRecommended = true,
            details = "Witness breathtaking panoramic views of Sarajevo from its surrounding hills and mountains. This tour takes you on a scenic journey to the highest points around the city, including Trebevic Mountain and its famous cable car ride. Enjoy stunning sights of the city nestled in the valley, surrounded by majestic peaks. Learn about the natural beauty of the region, hear stories of the 1984 Winter Olympics held in Sarajevo, and capture Instagram-worthy photos of the picturesque landscapes."
        ),
        HomeItemModel(
            id = 22,
            title = "Bridges of Sarajevo Bike",
            type = SectionEnum.TOUR,
            tourType = TourType.RECOMMENDED,
            rating = 4.8,
            address = "Sarajevo",
            isTour = true,
            price = 1,
            image = R.drawable.ic_tour4,
            city = "Sarajevo",
            cost = "10$",
            details = "Explore the charming bridges that span the Miljacka River on this exciting bike tour. Cycle along the riverbanks and discover the architectural wonders that connect different parts of Sarajevo. Admire the iconic Latin Bridge, known for its historical significance, and cross the Festina Lente Bridge, a modern marvel with its unique design. Your knowledgeable guide will provide insights into the engineering feats and cultural significance of each bridge, making this a memorable and informative experience."
        ),
        HomeItemModel(
            id = 23,
            title = "Art and Culture Stroll",
            type = SectionEnum.TOUR,
            tourType = TourType.POPULAR,
            rating = 4.4,
            address = "Sarajevo",
            price = 2,
            image = R.drawable.ic_tour5,
            city = "Sarajevo",
            cost = "15$",
            isTour = true,
            details = "Immerse yourself in Sarajevo's vibrant arts and culture scene on this leisurely stroll through the city's creative neighborhoods. Discover hidden art galleries showcasing local talent and visit contemporary art museums that highlight Bosnia and Herzegovina's rich artistic heritage. Engage with street performers and witness live music performances in Sarajevo's buzzing squares. Along the way, learn about the city's artistic legacy, its influence on the region, and the vibrant creative community that thrives here."
        ),
        HomeItemModel(
            id = 24,
            title = "Sarajevo's War History",
            type = SectionEnum.TOUR,
            tourType = TourType.RECOMMENDED,
            rating = 4.8,
            address = "Sarajevo",
            isTour = true,
            price = 2,
            image = R.drawable.ic_tour6,
            city = "Sarajevo",
            cost = "12$",
            details = "Embark on a culinary adventure through Sarajevo's vibrant food scene. This gastronomic tour introduces you to the city's diverse flavors and traditionaldishes. Indulge in delicious cevapi, a local specialty of grilled meat served with warm flatbread, or savor the hearty flavors of Sarajevski Stew. Explore the bustling markets and try authentic Bosnian sweets like baklava. Along the way, your knowledgeable guide will share insights into the cultural significance of the food and its connection to Sarajevo's history."
        )
    )
}
